export default {
  GET_ALL_ARTICLE: 'GET_ALL_ARTICLE',
  GET_ARTICLE_BY_ID: 'GET_ARTICLE_BY_ID',
  UPDATE_ARTICLE: 'UPDATE_ARTICLE',
  ADD_ARTICLE: 'ADD_ARTICLE',
  DELETE_ARTICLE: 'DELETE_ARTICLE',
  GET_ALL_ARTICLES_BY_CATEGORY: 'GET_ALL_ARTICLES_BY_CATEGORY',
  UPDATE_ARTICLE_CATEGORY: 'UPDATE_ARTICLE_CATEGORY',
};
