export default {
  GET_ALL_RECIPE: 'GET_ALL_RECIPE',
  GET_RECIPE_BY_ID: 'GET_RECIPE_BY_ID',
  UPDATE_RECIPE: 'UPDATE_RECIPE',
  ADD_RECIPE: 'ADD_RECIPE',
  DELETE_RECIPE: 'DELETE_RECIPE',
  GET_ALL_RECIPES_BY_CATEGORY: 'GET_ALL_RECIPES_BY_CATEGORY',
  UPDATE_RECIPE_CATEGORY: 'UPDATE_RECIPE_CATEGORY',
};
